[package]
name = "esh"
version = "0.1.0"
authors = ["sohei yamaga <me@eliza.link>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
nix = "0.15.0"
